### ISSUE TITLE
ps_coords_to_sfc option for XYZ

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/poisspatial#11]
should have option to create XYZ geometry from 3 columns, e.g. X, Y and elevation

**Comment by sebdalgarno** [comment]
This function could be useful as we can remove separate Elevation columns (often found in Gary's dbs) and integrate within XYZ dimension sfc columns (X, Y, Z = Elevation)

here is a first attempt:
```
ps_sfc_add_z <- function(x, sfc_column){
  x %<>% ps_activate_sfc(sfc_column)
  x %<>% cbind(st_coordinates(x))
  
  sfc <- st_sfc(do.call(list, lapply(1:nrow(x), function(y){
    z <- c(x$X[y], x$Y[y], x$Elevation[y])
    sfg <- st_point(z, dim = "XYZ")
    sfg
  })), crs = st_crs(x))
  
  sfc
}

fish$xyz <- ps_sfc_add_z(fish, "Observed")
```
However, I would like to make the following improvements (so far I've been unsuccessful):
1. make the function return x with the modified sfc_column, rather than return an sfc column
2. add arguments for Elevation column name (currently assumes it is called Elevation) and new column name (e.g. ObservedXYZ)

final implementation would look something like:
```
fish %<>% ps_sfc_add_z(sfc_column = "Observed", z_column = "Elevation", new_column = "ObservedXYZ")
```
Perhaps you could help with those improvements if you think it is valuable

**Comment by joethorley** [comment]
I think it's valuable and can look at early next week

**Comment by sebdalgarno** [comment]
this has been implemented with `ps_sfc_add_z()`...which can modify an existing sfc column. Thus this can be piped after `ps_coords_to_sfc()`.
