### ISSUE TITLE
ps_deactivate_sfc() strip attributes

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/poisspatial#14]
When I do `ps_deactivate_sfc(), the data.frame is no longer class 'sf', but some attributes associated with sf object remain.  This is just an observation - I haven't run into situations yet where this causes problems. As an example:

```
attr(recapture, "sf_column")
[1] "Observed"
> tmp <- ps_deactivate_sfc(recapture)
> attr(tmp, "sf_column")
[1] "Observed"
> ps_active_sfc_name(tmp)
character(0)
```

`recapture %<>% st_set_geometry(NULL)` removes attributes, but also completely removes the sfc column from the data.frame. Something in between might be better.

**Comment by sebdalgarno** [comment]
Ran into a problem related to this with ps_activate_sfc(). Running a dplyr mutate call reverts sf object back to original active sfc...I think this is because our ps_activate_sfc function does not change the underlying sf_column attribute. e.g.,

```
> sitelab %<>% ps_activate_sfc("center")
> ps_active_sfc_name(sitelab)
[1] "center"
> sitelab %<>% mutate(Label = "foo")
> ps_active_sfc_name(sitelab)
[1] "geometry"
```

**Comment by joethorley** [comment]
Ahh I wasn't aware of this - what do you know about the sf_column attribute?

**Comment by sebdalgarno** [comment]
A bit more on this...it seems to be more a problem with dplyr than poisspatial.
poisspatial:
```
> pt <- readRDS(system.file("sf/pt.rds", package = "poisspatial"))
> attr(pt, "sf_column")
[1] "geometry"
> pt %<>% ps_activate_sfc("geometry.2")
> attr(pt, "sf_column")
[1] "geometry.2"
```

dplyr:
```
> pt <- readRDS(system.file("sf/pt.rds", package = "poisspatial"))
> attr(pt, "sf_column")
[1] "geometry"
> pt %<>% mutate(id = 1)
> attr(pt, "sf_column")
NULL
```

**Comment by sebdalgarno** [comment]
`sf_column` attribute does not change with `dplyr::select` or `dplyr::filter`...only a problem with mutate

**Comment by joethorley** [comment]
then we either fix after use or override mutate so it does the fix

**Comment by joethorley** [comment]
its probably worth filing an issue with sf (after checking if its already been filed)

**Comment by sebdalgarno** [comment]
for now I am working around it by using `ps_activate_sfc()` after mutate in a pipeline. I will ckeck out sf issues and file one if doesn't already exist

**Comment by sebdalgarno** [comment]
filed issue with sf - https://github.com/r-spatial/sf/issues/552

**Comment by sebdalgarno** [comment]
issue fixed with sf: see https://github.com/r-spatial/sf/issues/552

**Comment by joethorley** [comment]
Good work!
