### ISSUE TITLE
ps_sfc_to_coords work with LINESTRINGS

### ISSUE THREAD

**Issue by joethorley** [poissonconsulting/poisspatial#28]
can you modify ps_sfc_to_coords() so that it works with LINESTRINGS and LINESTRINGS with Z coordinate. Currently it just takes POINTS and adds X and Y to each row. With LINESTRINGS it will need to copy each row for each point in the LINESTRING and add a Z column if the Z coordinate is present. Can you get done by end of play tomorrow?

note this ties in to issue #22

**Comment by sebdalgarno** [comment]
I think in this case we can just cast to point from line string with `sf::st_cast(x, "POINT")` and then convert to coordinates (including z if present).

Should we put casting within the `ps_sfc_to_coords` function? or leave as is and cast to point outside using sf?

**Comment by joethorley** [comment]
good question - I'll let you make that call

**Comment by joethorley** [comment]
note if you think we should go the route of doing the casting outside we should probably deprecate `ps_sfc_to_coords()` for something like `ps_sfc_points_to_coords()`

**Comment by sebdalgarno** [comment]
done and added tests.
if class is linestring of multiline string, the sfc is first cast to points
