### ISSUE TITLE
ps_coords_to_sfc work with multiple coords

### ISSUE THREAD

**Issue by joethorley** [poissonconsulting/poisspatial#29]
see also issue #28

**Comment by sebdalgarno** [comment]
is the idea here to create a new argument that provides name of the grouping variable?
Generally how this is done in sf is: `x %>% group_by(Var) %>% summaries(do_union = FALSE) %>% st_cast("LINESTRING")`

if we provide name of the grouping variable the above could be included in the poisspatial function
