### ISSUE TITLE
Actions failing due failing on install of `units` package

### ISSUE THREAD

**Issue by aylapear** [poissonconsulting/poisspatial#35]
In the dependencies section this is occurring

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘units’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
ERROR: lazy loading failed for package ‘poisspatial’
* removing ‘/Users/runner/work/_temp/Library/poisspatial’
Execution halted
Warning messages:
1: In i.p(...) : installation of package ‘units’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T//RtmpO6kYYh/file60f5c2b01bf/poisspatial_0.0.0.9027.tar.gz’ had non-zero exit status
3: In i.p(...) : installation of package ‘units’ had non-zero exit status
4: In i.p(...) : installation of package ‘units’ had non-zero exit status
5: In i.p(...) :
Which then causes the checks to fail due to the lack of poisspatial

checking package dependencies ... ERROR
Error:   Package required but not available: ‘poisspatial’
Package suggested but not available: ‘units’
At this point poisspatial is only being used for a single function in the code to read in the gpx files. Maybe there is another package/way to do this to get around this issue for now.

**Comment by joethorley** [comment]
This was fixed by Evan
