### ISSUE TITLE
option to retain original easting/northing columns for ps_coords_to_sfc()

### ISSUE THREAD

**Issue by sarahLy9** [poissonconsulting/poisspatial#45]
often convenient to have both the point coordinate column and easting/northing columns. might be nice to not have to covert back and forth with ps_sfc_to_coords()

**Comment by joethorley** [comment]
Yes good idea.

**Comment by joethorley** [comment]
@sarahLy9 - do you want to do a PR for this?

**Comment by sarahLy9** [comment]
sure! might take me a few weeks to get to it while I finish up CRM, but yes.
