### ISSUE TITLE
ps_nearest.sf non-matching sfc column names

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/poisspatial#6]
sqlite spatial files are read in by `sf::st_read()` with sfc column name "GEOMETRY". Prior to running `ps_nearest()` on two sf objects this has to be converted to "geometry" with 
```
x %<>% rename(geometry = GEOMETRY)
st_geometry(x) <- "geometry"
```
It would be sweet if this was automatically done within the function

**Comment by joethorley** [comment]
done
